language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq devscripts equivs lintian
- mk-build-deps -i -s sudo
script: debuild --preserve-env --preserve-envvar PATH -i -us -uc -b
after_success:
- sudo dpkg -i ../serial-latency-test*.deb
- sudo apt-get -f install
- serial-latency-test -V
- lintian -i ../serial-latency-test*.dsc
deploy:
  provider: releases
  api_key:
    secure: ictx5oc8uEoXKk4mgAjnhFMDcUsM/qS7sieNH8Xyn9oPQln/Acow0cK3AeDZ0nf7EJwSy5iD1c9D+/Gr3PaTLk/OQ/g5C/jpqQGYDRvISN9R8L2y13/bkq+rUfs+aQemQQmpqWqbkKbGH09TnciqICT8qN0EeBRRqEM+zz0ysSZafdU//9ldIdkYbIyoGuTtdWp09g4N+HncgKQwqKKNX2OB1SEhhPe86Mx048uRphU0tmKLvdjIgfyfksdlu1FGsfVNNF8jhMNYxuNQoa4N9Ohmhzwich0K/GDhUbeMkyhoyObUPxAxrmiyg17jPJ6/KjOqLHsxJs98Snh1C/72JfDQGb9APj6V2DjE6JP1qHwVs5gPlV7xMgcQVWKGZ1bvj+PmoGxkffxVNStUsSpyEz6O7HuS20a0aP7nvU9AZSAaFiKyik2OWlZ7L4d0rsK+7M62oVyTQKiPnFaZKyuuY7N7aTonwDrbmM8VYobOt3Cxbxk/tqaDinfkWNTKlpOyUqufeOhLwiU7DC4FEiwAP7QtRDtAtuv/mynnej5VxAPVFJDZObwLdsDAjzVjR6HLT3Slp2yVfuV351GKnBVKFRiT0ZA3guQEeWkUfa9Lb03wdlGGhbiI+Ifckiy+0qaWfA9NYy5wxHj496du3myEmPbtSJeTfzIVwAltblY+Pl8=
  file: "../serial-latency-test*.deb"
  on:
    repo: koppi/serial-latency-test
