language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq devscripts equivs lintian
- mk-build-deps -i -s sudo
script: debuild --preserve-env --preserve-envvar PATH -i -us -uc -b
after_success:
- sudo dpkg -i ../serial-latency-test*.deb
- sudo apt-get -f install
- serial-latency-test -V
- lintian -i ../serial-latency-test*.dsc
